# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.8.1
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: matrix-xmpp-appservice-development
  name: matrix-xmpp-appservice-development
spec:
  containers:
    - image: docker.io/library/postgres:17
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: synapse
        - name: POSTGRES_INITDB_ARGS
          value: --encoding=UTF-8 --lc-collate=C --lc-ctype=C
      name: postgres
      volumeMounts:
        - mountPath: /var/lib/postgresql/data:Z
          name: matrix-xmpp-appservice-development-postgres-pvc
    - image: docker.io/matrixdotorg/synapse:latest
      name: synapse
      volumeMounts:
        - mountPath: /data:Z
          name: matrix-xmpp-appservice-development-matrix-pvc
  volumes:
    - name: matrix-xmpp-appservice-development-postgres-pvc
      persistentVolumeClaim:
        claimName: matrix-xmpp-appservice-development-postgres
    - name: matrix-xmpp-appservice-development-matrix-pvc
      persistentVolumeClaim:
        claimName: matrix-xmpp-appservice-development-matrix
